[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
DJANGO_SETTINGS_MODULE = "reportme.settings_railway"
DEBUG = "False"
PYTHONPATH = "/app"
RAILWAY_DOCKERFILE_BUILD = "true"
FORCE_DOCKERFILE = "true"