[build]
builder = "dockerfile"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
DJANGO_SETTINGS_MODULE = "reportme.settings_railway"
DEBUG = "False"
PYTHONPATH = "/app"
NIXPACKS_BUILD_CMD = "docker"