# Generated by Django 5.2.6 on 2025-10-02 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Parâmetro')),
                ('type', models.CharField(choices=[('string', 'Texto'), ('number', 'Número'), ('date', 'Data'), ('datetime', 'Data e Hora'), ('boolean', 'Verdadeiro/Falso'), ('list', 'Lista')], default='string', max_length=50, verbose_name='Tipo')),
                ('allow_null', models.BooleanField(default=False, verbose_name='Permite Vazio')),
                ('default_value', models.CharField(blank=True, max_length=255, verbose_name='Valor Padrão')),
                ('allow_multiple_values', models.BooleanField(default=False, verbose_name='Permite Múltiplos Valores')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Valor Mínimo')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Valor Máximo')),
                ('regex_pattern', models.CharField(blank=True, max_length=500, verbose_name='Padrão Regex')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Opções (para tipo lista)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parâmetro',
                'verbose_name_plural': 'Parâmetros',
                'db_table': 'core_parameter',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Conexão')),
                ('database', models.CharField(max_length=255, verbose_name='Nome do Banco')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='Host')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='Porta')),
                ('user', models.CharField(blank=True, max_length=255, verbose_name='Usuário')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='Senha')),
                ('sgbd', models.CharField(choices=[('sqlite', 'SQLite'), ('postgresql', 'PostgreSQL'), ('sqlserver', 'SQL Server'), ('oracle', 'Oracle'), ('mysql', 'MySQL')], default='sqlite', max_length=20, verbose_name='SGBD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_config', models.JSONField(blank=True, default=dict, verbose_name='Configurações Extras')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexão',
                'verbose_name_plural': 'Conexões',
                'db_table': 'core_connection',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Projeto')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'core_project',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Nó')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.connection', verbose_name='Conexão')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.projectnode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.project')),
            ],
            options={
                'verbose_name': 'Nó do Projeto',
                'verbose_name_plural': 'Nós do Projeto',
                'db_table': 'core_project_node',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='first_node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_root', to='core.projectnode'),
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Consulta')),
                ('query', models.TextField(verbose_name='Consulta SQL')),
                ('timeout', models.IntegerField(default=30, verbose_name='Timeout (segundos)')),
                ('cache_duration', models.IntegerField(default=0, verbose_name='Cache (segundos, 0 = sem cache)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='core.connection', verbose_name='Conexão')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'core_query',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='projectnode',
            name='query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.query', verbose_name='Consulta'),
        ),
        migrations.CreateModel(
            name='QueryExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parâmetros Utilizados')),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro'), ('timeout', 'Timeout')], default='success', max_length=20)),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Tempo de Execução (segundos)')),
                ('rows_returned', models.IntegerField(blank=True, null=True, verbose_name='Linhas Retornadas')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.query')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execução de Consulta',
                'verbose_name_plural': 'Execuções de Consultas',
                'db_table': 'core_query_execution',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parameter')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.query')),
            ],
            options={
                'db_table': 'core_query_parameter',
                'ordering': ['order', 'parameter__name'],
                'unique_together': {('query', 'parameter')},
            },
        ),
        migrations.AddField(
            model_name='query',
            name='parameters',
            field=models.ManyToManyField(blank=True, through='core.QueryParameter', to='core.parameter', verbose_name='Parâmetros'),
        ),
        migrations.AlterUniqueTogether(
            name='projectnode',
            unique_together={('project', 'parent', 'name')},
        ),
    ]
