# Generated by Django 5.2.6 on 2025-10-14 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='parameters',
        ),
        migrations.AddField(
            model_name='parameter',
            name='query',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='query_parameters', to='core.query', verbose_name='Consulta'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QueryParameter',
        ),
    ]
